spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.15.76:3306/jwt?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  redis:
    database: 6   # Redis数据库索引（默认为0）
    host: 116.62.15.76  # Redis服务器地址
    port: 6379         # Redis服务器连接端口
    password:    # Redis服务器连接密码（默认为空）
    max-wait: 30000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-active: 100   # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 20     # 连接池中的最大空闲连接
    min-idle: 0     # 连接池中的最小空闲连接
    timeout: 5000  # 连接超时时间（毫秒）
  #自定义配置
  redis2:
    database: 5   # Redis数据库索引（默认为0）
    host: 116.62.15.76  # Redis服务器地址，若测试也可以用127.0.0.1本地的redis，因为database索引库用的不是一个
    port: 6379         # Redis服务器连接端口
    password:    # Redis服务器连接密码（默认为空）
    timeout: 5000  # 连接超时时间（毫秒）


logging:
  file:
    path: C:\Users\Administrator\Desktop\jwtlog




